
var jokes = [
    { item: 'Cash',conclusion: 'No thanks, I prefer peanuts.'},
    { item: 'Owls',conclusion: 'Yes, they do.'},
    { item: 'kanga', conclusion: 'Actually, it\'s kangaroo.' },
    { item: 'Deja', conclusion: `<say-as interpret-as="interjection">knock knock</say-as>` },
    { item: 'An extraterrestrial', conclusion: 'Wait, how many extrateresstrial do you know?' },
    { item: 'Spell', conclusion: `<say-as interpret-as="spell-out">WHO</say-as>`},
    { item: 'Hatch', conclusion: 'God bless you.' },
    { item: 'Doris', conclusion: 'Doris locked, that\'s why I had to knock.' },
    { item: 'Nobel', conclusion: 'No bell, so I\'ll knock.' },
    { item: 'Bless', conclusion: 'I didn\'t sneeze!' },
    { item: 'Broccoli', conclusion: 'Broccoli doesn\'t have a last name, silly.' },
    { item: 'Olive', conclusion: 'Olive right next door to you.' },
    { item: 'Figs', conclusion: 'Figs the doorbell, it\'s broken!' },
    { item: 'Ketchup', conclusion: 'Ketchup with me and I\'ll tell you!' },
    { item: 'Doughnut', conclusion: `Do not ask, it's a secret! <amazon:effect name="whispered">I am not a real human.</amazon:effect>.` },
    { item: 'Barbie', conclusion: 'Barbie Q Chicken!' },
    { item: 'Howard', conclusion: 'Howard I know?' },
    { item: 'Ken', conclusion: 'Ken I come in, it\'s freezing out here?' },
    { item: 'Lena', conclusion: 'Lena little closer and I’ll tell you!' },
    { item: 'Luke', conclusion: 'Look through the keyhole to see!' },
    { item: 'Alpaca', conclusion: 'Alpaca the trunk, you pack the suitcase!' },
    { item: 'Goat', conclusion: 'Goat to the door and find out.' },
    { item: 'Doctor', conclusion: 'You’ve seen that TV show?' },
    { item: 'Dozen', conclusion: 'Dozen anyone want to let me in?' },
    { item: 'From', conclusion: `Actually, grammatically speaking you should say "from whom."` },
    { item: 'Nun', conclusion: `Our business is our business. None of your business! <say-as interpret-as="interjection">ha</say-as>` },
    { item: 'Water', conclusion: `Water you doing in my house?` },
    { item: 'Who!', conclusion: `That’s what an owl says!` },
    { item: 'Witches', conclusion: `Witches the way home?` },
    { item: 'Cow says', conclusion: `No, a cow says <say-as interpret-as="interjection">moo</say-as>` },
    { item: 'Annie', conclusion: `Anything you can do, I can do better.` },
    { item: 'Hatch', conclusion: `Bless you, my friend.` },
    { item: 'Robin', conclusion: `Robin you, now hand over the cash.` },
    { item: 'Tank', conclusion: `You're welcome.` },
    { item: 'Ya', conclusion: `Yahoo! I’m just as psyched to see you!` },
    { item: 'Stopwatch', conclusion: `Stopwatch you’re doing and pay attention!` },
    { item: 'Stupid', conclusion: `Stupid you, that’s who.` },
    { item: 'Amos', conclusion: `A mosquito.` },
    { item: 'Adore', conclusion: `Adore is between us. Open up! ` },
    { item: 'Abby', conclusion: `A bee just stung me!` },
    { item: 'Caesar', conclusion: `Caesar quick, she’s running away.` },
    { item: 'Claire', conclusion: `Claire the way, I’m coming through!` },
    { item: 'Harry', conclusion: `Harry up and open this door!` },
    { item: 'Hockey', conclusion: `Hockey doesn't work, so I had to knock!` },
    { item: 'Kenya', conclusion: `Kenya guess who is it?` },
    { item: 'Kermit', conclusion: `Commit a crime and you'll get locked up!` },
    { item: 'Major', conclusion: `Made your day with this joke, haven’t I? ` },
    { item: 'Mary', conclusion: `Marry me? <say-as interpret-as="interjection">aw</say-as>` },
    { item: 'Suspense', conclusion: `<audio src='http s://s3.amazonaws.com/ask-soundlibrary/foley/amzn_sfx_sleigh_bells_02.mp3'/>` },
    { item: 'Tennis', conclusion: `<say-as interpret-as="interjection">duh</say-as>Ten is five plus five!` },
    { item: 'Comb', conclusion: `Comb on down and I'll tell you!` },
];

module.exports = jokes;